spring:
  profiles:
    active: local
  application:
    name: Gym App Backend
---
jwt:
  secret: my-secret-key-which-needs-to-be-at-least-32-characters-long
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app_db
    username: gym_app_user
    password: gym_app_pass

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
