spring:
  profiles:
    active: local
  application:
    name: Gym App Backend
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app_db
    username: gym_app_user
    password: gym_app_pass

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true