spring:
  profiles:
    active: local
  application:
    name: Gym App Backend

---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_FILE_SIZE}

  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app_db
    username: gym_app_user
    password: gym_app_pass
    hikari:
      auto-commit: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: sourcery.graduates@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: health

  kafka:
    replicas: 3
    partitions: 3
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: gym-app-listener-group
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      account-register: "userProfile.create-account"
      email-send: "email.send-email"
      retry: "common.RETRY"
      dead-letter: "common.DLT"

frontend:
  base_url: "http://localhost:3000"
  registration_verification_path: "/registerVerification?token="
  password_reset_path: "/passwordReset?token="

app:
  base_url: "http://localhost:8080"

google:
  client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
  client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
