spring:
  profiles:
    active: local
  application:
    name: Gym App Email Service
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app_db
    username: gym_app_user
    password: gym_app_pass
    hikari:
      auto-commit: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: sourcery.graduates@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: health

  kafka:
    replicas: 1
    partitions: 1
    aggregation:
      like-notification:
        interval-minutes: 1440
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: gym-app-listener-group
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      user-reminder: "authentication.user-reminder"
      account-register: "userProfile.create-account"
      likes-events: "workout.like-events"
      likes-notifications: "userProfile.notifications-likes-dislikes"
      last-user-workout: "workout.last-user-workout"
      email-send: "email.send-email"
      email-retry: "email.email-retry"
      retry: "common.RETRY"
      dead-letter: "common.DLT"
    streams:
      application-id: gym-app-backend-streams-single-broker
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

logging:
  level:
    kafka: WARN
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.streams: WARN